name: Deploy Azure Static Web Apps

# https://github.com/actions/starter-workflows/blob/main/pages/nextjs.yml

on:
  push:
    branches:
      - main

env:
  SWA_NAME: "thaitype-dev"

  # Retry Config
  RETRY_TIMEOUT_MINUTES: 2
  RETRY_MAX_ATTEMPTS: 3
  RETRY_DELAY_SECONDS: 5

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.5.x
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build

      - name: Deploy to Azure Static Web Apps
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: ${{ env.RETRY_TIMEOUT_MINUTES }}
          max_attempts: ${{ env.RETRY_MAX_ATTEMPTS }}
          polling_interval_seconds: ${{ env.RETRY_DELAY_SECONDS }}
          command: npx @azure/static-web-apps-cli deploy ./out --env production -n  ${{ env.SWA_NAME }}
        env:
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_FIELD_0B95C8200 }}
